package com.pbec.preboardexamchecker.ui.theme

import androidx.compose.ui.graphics.Color

// APE-C brand palette: teal-blue accent, navy "blueprint" dark surfaces.
// Dark primary is a lighter accent (#3AACCC) so icons/indicators stay legible on dark.

val md_theme_light_primary = Color(0xFF0A7EA4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC5E7F2)
val md_theme_light_onPrimaryContainer = Color(0xFF002A38)
val md_theme_light_secondary = Color(0xFF3D5070)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE9F2)
val md_theme_light_onSecondaryContainer = Color(0xFF002A38)
val md_theme_light_tertiary = Color(0xFF0F766E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC9F2E9)
val md_theme_light_onTertiaryContainer = Color(0xFF00201A)
// Readable red for destructive UI; the brighter #FF6B6B is reserved for the semantic fail token.
val md_theme_light_error = Color(0xFFC5303A)
val md_theme_light_errorContainer = Color(0xFFFFE2E2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0E)
val md_theme_light_background = Color(0xFFF0F6FA)
val md_theme_light_onBackground = Color(0xFF0C1322)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0C1322)
val md_theme_light_surfaceVariant = Color(0xFFE4EEF5)
val md_theme_light_onSurfaceVariant = Color(0xFF3D5070)
val md_theme_light_outline = Color(0xFF7A96B8)
val md_theme_light_inverseOnSurface = Color(0xFFEDF2FF)
val md_theme_light_inverseSurface = Color(0xFF1A2845)
val md_theme_light_inversePrimary = Color(0xFF3AACCC)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0A7EA4)
val md_theme_light_outlineVariant = Color(0xFFC8DDE8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF3AACCC)
val md_theme_dark_onPrimary = Color(0xFF06222E)
val md_theme_dark_primaryContainer = Color(0xFF0E3A4A)
val md_theme_dark_onPrimaryContainer = Color(0xFFC5E7F2)
val md_theme_dark_secondary = Color(0xFF8BA4CC)
val md_theme_dark_onSecondary = Color(0xFF0C1322)
val md_theme_dark_secondaryContainer = Color(0xFF1A2845)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDF2FF)
val md_theme_dark_tertiary = Color(0xFF34D0AE)
val md_theme_dark_onTertiary = Color(0xFF00201A)
val md_theme_dark_tertiaryContainer = Color(0xFF0F3B30)
val md_theme_dark_onTertiaryContainer = Color(0xFFB8F5E4)
val md_theme_dark_error = Color(0xFFFF6B6B)
val md_theme_dark_errorContainer = Color(0xFF5C1A1A)
val md_theme_dark_onError = Color(0xFF410E0E)
val md_theme_dark_onErrorContainer = Color(0xFFFFD9D9)
val md_theme_dark_background = Color(0xFF0C1322)
val md_theme_dark_onBackground = Color(0xFFEDF2FF)
val md_theme_dark_surface = Color(0xFF131E33)
val md_theme_dark_onSurface = Color(0xFFEDF2FF)
val md_theme_dark_surfaceVariant = Color(0xFF1A2845)
val md_theme_dark_onSurfaceVariant = Color(0xFF8BA4CC)
val md_theme_dark_outline = Color(0xFF4A6080)
val md_theme_dark_inverseOnSurface = Color(0xFF0C1322)
val md_theme_dark_inverseSurface = Color(0xFFEDF2FF)
val md_theme_dark_inversePrimary = Color(0xFF0A7EA4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF3AACCC)
val md_theme_dark_outlineVariant = Color(0xFF243454)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF0A7EA4)

// Header bar: fixed teal in both themes (M3 primary diverges per-mode, so it can't drive this).
val brand_header = Color(0xFF0A7EA4)
val brand_header_selection = Color(0xFF085F7D)

// Semantic scan-result colors. Outside the M3 scheme; surfaced via LocalExtendedColors.
val brand_light_pass = Color(0xFF22D3A0)
val brand_light_passContainer = Color(0xFFD6F3E8)
val brand_light_onPassContainer = Color(0xFF0B6B4E)
val brand_light_fail = Color(0xFFFF6B6B)
val brand_light_failContainer = Color(0xFFFFE2E2)
val brand_light_onFailContainer = Color(0xFF7A1212)
val brand_light_warning = Color(0xFFFFB347)
val brand_light_warningContainer = Color(0xFFFBEBD2)
val brand_light_onWarningContainer = Color(0xFF5A3A0A)
val brand_light_blankContainer = Color(0xFFE4EEF5)
val brand_light_onBlankContainer = Color(0xFF3D5070)

val brand_dark_pass = Color(0xFF22D3A0)
val brand_dark_passContainer = Color(0xFF122A1F)
val brand_dark_onPassContainer = Color(0xFF22D3A0)
val brand_dark_fail = Color(0xFFFF6B6B)
val brand_dark_failContainer = Color(0xFF2D1212)
val brand_dark_onFailContainer = Color(0xFFFF6B6B)
val brand_dark_warning = Color(0xFFFFB347)
val brand_dark_warningContainer = Color(0xFF2A2212)
val brand_dark_onWarningContainer = Color(0xFFFFB347)
val brand_dark_blankContainer = Color(0xFF1A2845)
val brand_dark_onBlankContainer = Color(0xFF8BA4CC)
